_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  auto_entitylabel: -100
  address: 0
  admin_toolbar: 0
  announcements_feed: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  config: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  form_options_attributes: 0
  formblock: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  jquery_ui: 0
  link: 0
  markup: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_features: 0
  path: 0
  path_alias: 0
  profile: 0
  search: 0
  select2: 0
  select2_publish: 0
  shortcut: 0
  state_machine: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  w_select_with_image: 0
  hide_revision_field: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  stable9: 0
  kart: 0
  kart_subtheme: 0
  webshop_theme: 0
profile: standard
