_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: e8ac0bf0-48d8-4b01-9caf-cf3f602c23f2
name: 'Drush Site-Install'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /product/2
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
